# Generated by Django 6.0.3 on 2026-03-30 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('maintenance', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_expenses', to='maintenance.maintenance', verbose_name='Maintenance liée'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='vehicles.vehicle', verbose_name='Véhicule'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['fiscal_year'], name='expenses_bu_fiscal__67e461_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['start_date', 'end_date'], name='expenses_bu_start_d_43a314_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['vehicle', 'expense_type'], name='expenses_ex_vehicle_2352c0_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='expenses_ex_expense_cf8a73_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_paid'], name='expenses_ex_is_paid_4f7667_idx'),
        ),
    ]
