# Generated by Django 6.0.3 on 2026-04-13 04:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0005_remove_reservation_completed_at_and_more'),
        ('vehicles', '0005_busroute_heure_arrivee_busroute_heure_depart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('card_number', models.CharField(help_text='Ex: 5288 **** **** 1234', max_length=50, unique=True, verbose_name='Numéro de carte')),
                ('card_network', models.CharField(choices=[('BOCOM', 'BOCOM'), ('TOTAL', 'TOTAL'), ('TRADEX', 'TRADEX')], default='BOCOM', max_length=30, verbose_name='Réseau')),
                ('category', models.CharField(choices=[('BUS_SCOLAIRE', 'Bus scolaire'), ('BUS_ORDINAIRE', 'Bus ordinaire'), ('UTILITAIRE', 'Utilitaire / Tourisme'), ('FONCTION', 'Véhicule de fonction')], default='UTILITAIRE', max_length=20, verbose_name='Catégorie véhicule')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_card', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Carte carburant',
                'verbose_name_plural': 'Cartes carburant',
                'ordering': ['vehicle__registration_number'],
            },
        ),
        migrations.CreateModel(
            name='FuelTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('transaction_type', models.CharField(choices=[('RAMASSAGE', 'Ramassage scolaire'), ('MISSION', 'Mission / Réservation'), ('AUTRE', 'Autre')], default='RAMASSAGE', max_length=20, verbose_name='Type')),
                ('transaction_date', models.DateTimeField(verbose_name='Date')),
                ('gas_station', models.CharField(blank=True, max_length=200, verbose_name='Station service')),
                ('quantity_liters', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Litres')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix/litre (FCFA)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total (FCFA)')),
                ('mileage_at_refuel', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kilométrage')),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='fuel/receipts/%Y/%m/', verbose_name='Reçu')),
                ('receipt_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fuel.fuelcard', verbose_name='Carte')),
                ('driver', models.ForeignKey(limit_choices_to={'role__in': ['CHAUFFEUR']}, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_transactions_done', to=settings.AUTH_USER_MODEL, verbose_name='Chauffeur')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_transactions', to='reservations.reservation', verbose_name='Mission liée')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction carburant',
                'verbose_name_plural': 'Transactions carburant',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['card', 'transaction_date'], name='fuel_fueltr_card_id_96645b_idx'), models.Index(fields=['driver', 'status'], name='fuel_fueltr_driver__4e09d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyFuelAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Mois')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Année')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant alloué (FCFA)')),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_allocations_approved', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='fuel.fuelcard', verbose_name='Carte')),
            ],
            options={
                'verbose_name': 'Allocation mensuelle carburant',
                'verbose_name_plural': 'Allocations mensuelles carburant',
                'ordering': ['-year', '-month'],
                'unique_together': {('card', 'month', 'year')},
            },
        ),
    ]
