# Generated by Django 6.0.3 on 2026-04-05 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('vehicles', '0003_vehicle_assigned_director_vehicle_assignment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, help_text='Uniquement pour les chauffeurs bus scolaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_driver', to='vehicles.vehicle', verbose_name='Bus assigné'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='assignment_type',
            field=models.CharField(choices=[('POOL', 'Chauffeur polyvalent'), ('BUS_SCOLAIRE', 'Chauffeur bus scolaire')], default='POOL', max_length=20, verbose_name="Type d'affectation"),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='bus_slot_end',
            field=models.TimeField(blank=True, default=None, help_text='Ex: 08:30', null=True, verbose_name='Fin créneau bus'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='bus_slot_start',
            field=models.TimeField(blank=True, default=None, help_text='Ex: 05:00 — automatique si BUS_SCOLAIRE', null=True, verbose_name='Début créneau bus'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='manual_status',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_MISSION', 'En mission'), ('INDISPONIBLE', 'Indisponible'), ('CONGE', 'En congé')], default='DISPONIBLE', max_length=20, verbose_name='Statut manuel'),
        ),
    ]
