# Generated by Django 6.0.3 on 2026-04-08 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('vehicles', '0003_vehicle_assigned_director_vehicle_assignment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=20, unique=True)),
                ('school', models.CharField(blank=True, choices=[('3IAC', '3IAC — Informatique'), ('ISTDI', 'ISTDI — Technologies & Design'), ('ICIA', "ICIA — Commerce & Ingénierie d'Affaires"), ('SEAS', 'SEAS — Ingénierie anglophone'), ('GRADUATE_SCHOOL', 'IUC Graduate School')], default='', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, help_text='Uniquement pour les chauffeurs bus scolaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_driver', to='vehicles.vehicle', verbose_name='Bus assigné'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='assignment_type',
            field=models.CharField(choices=[('POOL', 'Chauffeur polyvalent'), ('BUS_SCOLAIRE', 'Chauffeur bus scolaire')], default='POOL', max_length=20, verbose_name="Type d'affectation"),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='bus_slot_end',
            field=models.TimeField(blank=True, default=None, help_text='Ex: 08:30', null=True, verbose_name='Fin créneau bus'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='bus_slot_start',
            field=models.TimeField(blank=True, default=None, help_text='Ex: 05:00 — automatique si BUS_SCOLAIRE', null=True, verbose_name='Début créneau bus'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='manual_status',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_MISSION', 'En mission'), ('INDISPONIBLE', 'Indisponible'), ('CONGE', 'En congé')], default='DISPONIBLE', max_length=20, verbose_name='Statut manuel'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_vehicle',
            field=models.OneToOneField(blank=True, help_text='Uniquement pour les directeurs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_user', to='vehicles.vehicle', verbose_name='Véhicule de fonction assigné'),
        ),
        migrations.AddField(
            model_name='user',
            name='personnel_type',
            field=models.CharField(blank=True, choices=[('DIRECTEUR', 'Directeur'), ('CHEF_DEPT', 'Chef de département'), ('AUTRE', 'Autre personnel')], default='', max_length=20, verbose_name='Type de personnel'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.department', verbose_name='Département'),
        ),
        migrations.CreateModel(
            name='StaffRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role_hint', models.CharField(choices=[('PERSONNEL', 'Personnel'), ('CHAUFFEUR', 'Chauffeur'), ('TECHNICIEN', 'Technicien')], default='PERSONNEL', max_length=20, verbose_name='Rôle suggéré')),
                ('personnel_type_hint', models.CharField(blank=True, choices=[('DIRECTEUR', 'Directeur'), ('CHEF_DEPT', 'Chef de département'), ('AUTRE', 'Autre personnel')], default='', max_length=20, verbose_name='Type suggéré')),
                ('is_activated', models.BooleanField(default=False, help_text='True si un compte utilisateur existe déjà pour ce matricule', verbose_name='Compte créé')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_members', to='users.department')),
            ],
            options={
                'verbose_name': 'Registre du personnel',
                'verbose_name_plural': 'Registre du personnel',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
