# Generated by Django 6.0.3 on 2026-04-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_driverprofile_assigned_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, choices=[('3IAC', '3IAC — Informatique'), ('ISTDI', 'ISTDI — Technologies & Design'), ('ICIA', "ICIA — Commerce & Ingénierie d'Affaires"), ('SEAS', 'SEAS — Ingénierie anglophone'), ('GRADUATE_SCHOOL', 'IUC Graduate School')], default='', max_length=20, verbose_name='École'),
        ),
    ]
