# Generated by Django 6.0.3 on 2026-04-05 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driverprofile_assigned_vehicle_and_more'),
        ('vehicles', '0004_vehicle_bus_driver_alter_vehicle_assignment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_vehicle',
            field=models.OneToOneField(blank=True, help_text='Uniquement pour les directeurs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_user', to='vehicles.vehicle', verbose_name='Véhicule de fonction assigné'),
        ),
        migrations.AddField(
            model_name='user',
            name='personnel_type',
            field=models.CharField(blank=True, choices=[('DIRECTEUR', 'Directeur'), ('CHEF_DEPT', 'Chef de département'), ('AUTRE', 'Autre personnel')], default='', max_length=20, verbose_name='Type de personnel'),
        ),
    ]
