# Generated by Django 6.0.3 on 2026-04-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, choices=[('3IAC', '3IAC'), ('ISTDI', 'ISTDI'), ('ICIA', 'ICIA'), ('SEAS', 'SEAS'), ('GRADUATE_SCHOOL', 'Graduate School')], default='', max_length=20, verbose_name='École'),
        ),
    ]
