# Generated by Django 6.0.3 on 2026-04-06 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_department_alter_user_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('role_hint', models.CharField(choices=[('PERSONNEL', 'Personnel'), ('CHAUFFEUR', 'Chauffeur'), ('TECHNICIEN', 'Technicien')], default='PERSONNEL', max_length=20, verbose_name='Rôle suggéré')),
                ('personnel_type_hint', models.CharField(blank=True, choices=[('DIRECTEUR', 'Directeur'), ('CHEF_DEPT', 'Chef de département'), ('AUTRE', 'Autre personnel')], default='', max_length=20, verbose_name='Type suggéré')),
                ('is_activated', models.BooleanField(default=False, help_text='True si un compte utilisateur existe déjà pour ce matricule', verbose_name='Compte créé')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_members', to='users.department')),
            ],
            options={
                'verbose_name': 'Registre du personnel',
                'verbose_name_plural': 'Registre du personnel',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
