# Generated by Django 6.0.3 on 2026-04-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['expiry_date']},
        ),
        migrations.AddField(
            model_name='document',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('insurance', 'Assurance'), ('registration', 'Carte grise'), ('inspection', 'Visite technique'), ('vignette', 'Vignette automobile'), ('other', 'Autre')], max_length=20),
        ),
    ]
