# Generated by Django 6.0.3 on 2026-03-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('TOURISME', 'Tourisme'), ('UTILITAIRE', 'Utilitaire'), ('BUS', 'Bus')], default='TOURISME', help_text='TOURISME=<10 places, UTILITAIRE=10-19 places, BUS=20+ places', max_length=20, verbose_name='Catégorie'),
        ),
    ]
