# Generated by Django 6.0.3 on 2026-04-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='assigned_director',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Directeur assigné'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assignment_type',
            field=models.CharField(choices=[('POOL', 'Parc commun'), ('FONCTION', 'Voiture de fonction')], default='POOL', max_length=20, verbose_name="Type d'affectation"),
        ),
    ]
