# Generated by Django 6.0.3 on 2026-04-05 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_assigned_director_vehicle_assignment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='bus_driver',
            field=models.ForeignKey(blank=True, help_text='Uniquement pour les bus scolaires — ramassage matin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Chauffeur bus assigné'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='assignment_type',
            field=models.CharField(choices=[('POOL', 'Parc commun'), ('FONCTION', 'Voiture de fonction'), ('BUS_SCOLAIRE', 'Bus scolaire')], default='POOL', max_length=20, verbose_name="Type d'affectation"),
        ),
    ]
