# Generated by Django 6.0.3 on 2026-04-11 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial_squashed_0003_vehicle_assigned_director_vehicle_assignment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligne', models.CharField(max_length=1)),
                ('nom_trajet', models.CharField(max_length=100)),
                ('point_depart', models.CharField(max_length=100)),
                ('point_arrivee', models.CharField(default='IUC Logbessou', max_length=100)),
                ('nb_tours', models.IntegerField(default=2)),
                ('jours_service', models.JSONField(default=list)),
                ('arrets', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bus_route', to='vehicles.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='BusRouteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('EFFECTUE', 'Effectué'), ('RETARD', 'Effectué avec retard'), ('ANNULE', 'Annulé'), ('INCIDENT', 'Incident signalé')], default='EFFECTUE', max_length=20)),
                ('heure_depart_reelle', models.TimeField(blank=True, null=True)),
                ('heure_arrivee_reelle', models.TimeField(blank=True, null=True)),
                ('nb_passagers', models.IntegerField(default=0)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='vehicles.busroute')),
            ],
            options={
                'unique_together': {('route', 'date')},
            },
        ),
    ]
