# Generated by Django 6.0.3 on 2026-04-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_busroute_busroutelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='heure_arrivee',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busroute',
            name='heure_depart',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
