# Generated by Django 6.0.3 on 2026-03-30 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Assigné par le gestionnaire après validation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='vehicles.vehicle', verbose_name='Véhicule'),
        ),
    ]
