# Generated by Django 6.0.3 on 2026-04-11 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_vehicle'),
        ('vehicles', '0005_busroute_heure_arrivee_busroute_heure_depart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointageChauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('EFFECTUE', 'Effectué'), ('RETARD', 'Effectué avec retard'), ('ANNULE', 'Annulé'), ('INCIDENT', 'Incident signalé')], default='EFFECTUE', max_length=20)),
                ('heure_depart_reelle', models.TimeField(blank=True, null=True)),
                ('heure_arrivee_reelle', models.TimeField(blank=True, null=True)),
                ('nb_passagers', models.PositiveSmallIntegerField(default=0)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('chauffeur', models.ForeignKey(limit_choices_to={'role': 'CHAUFFEUR'}, on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'pointages_chauffeur',
                'ordering': ['-date'],
                'unique_together': {('chauffeur', 'date')},
            },
        ),
    ]
