# Generated by Django 6.0.3 on 2026-04-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_pointagechauffeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Complété le'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='driver_acceptance',
            field=models.CharField(blank=True, choices=[('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], max_length=10, null=True, verbose_name='Acceptation chauffeur'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='driver_acceptance_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse chauffeur'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='driver_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire chauffeur'),
        ),
    ]
