# Generated by Django 6.0.3 on 2026-04-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='driver_acceptance',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='driver_acceptance_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='driver_comment',
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
    ]
