# Generated by Django 6.0.3 on 2026-04-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='location',
            field=models.CharField(blank=True, default='', help_text="Lieu où la panne s'est produite", max_length=200, verbose_name='Localisation'),
        ),
    ]
