# Generated by Django 6.0.3 on 2026-05-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_breakdown_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='status',
            field=models.CharField(choices=[('SIGNALE', 'Signalé'), ('EN_DIAGNOSTIC', 'En diagnostic'), ('EN_REPARATION', 'En réparation'), ('TRANSFERE_MAINT', 'Transféré en maintenance'), ('REPARE', 'Réparé'), ('NON_REPARABLE', 'Non réparable')], default='SIGNALE', max_length=20, verbose_name='Statut'),
        ),
    ]
